[package]
name = "kernel-semantic-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernel-persistent = { path = "../kernel-persistent" }
kernel-schema = { path = "../kernel-schema" }
kernel-types = { path = "../kernel-types" }

[lints]
workspace = true
