[package]
name = "cfmd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Public Rust application facade for CFMD"

[dependencies]
cfmd-runtime = { path = "../cfmd-runtime" }
cfmd-derive = { path = "../cfmd-derive" }

[lints]
workspace = true
