use std::{marker::PhantomData, ops::Deref, path::PathBuf, sync::Arc};

use crate::{
    CandidatePreview, CommitOutcome, Database, DatabaseBuilder, Encryption, GroupKey, History,
    HistoryEntry, Object, ObjectGroupQuery, ObjectProjectionQuery, ObjectQuery, ObjectSet,
    OrderedObjectValue, Projection, PublicationNotifier, ReadContext, Result, RevisionId, Schema,
    Storage, Transaction, TransactionReadiness,
};

/// Static, explicit composition of the entity sets that belong to one database model.
///
/// Implementations are normally generated by `#[derive(CfmdSchema)]`. Merely deriving an entity
/// never registers it globally: each schema root chooses its own members explicitly.
pub trait CfmdSchema: Sized {
    #[doc(hidden)]
    type DefinitionAuthority;

    fn definition() -> Result<Schema>;

    #[doc(hidden)]
    fn __bind(source: Arc<ContextSource>) -> Result<Self>;

    #[must_use]
    fn database(path: impl Into<PathBuf>) -> SchemaDatabaseBuilder<Self> {
        SchemaDatabaseBuilder::new(path)
    }
}

/// Marker emitted only for `#[derive(CfmdEntity)]` types that explicitly opt into
/// `#[cfmd(authoritative)]` database-definition authority.
#[doc(hidden)]
pub trait AuthoritativeObject: Object {}

#[doc(hidden)]
pub struct SchemaAuthorityEmpty;

#[doc(hidden)]
pub struct SchemaAuthorityLeaf<E>(PhantomData<fn() -> E>);

#[doc(hidden)]
pub struct SchemaAuthorityPair<L, R>(PhantomData<fn() -> (L, R)>);

#[doc(hidden)]
pub trait CompleteSchemaAuthority {}

impl CompleteSchemaAuthority for SchemaAuthorityEmpty {}

impl<E: AuthoritativeObject> CompleteSchemaAuthority for SchemaAuthorityLeaf<E> {}

impl<L: CompleteSchemaAuthority, R: CompleteSchemaAuthority> CompleteSchemaAuthority
    for SchemaAuthorityPair<L, R>
{
}

/// A typed schema whose complete member set explicitly opted into persisted database-definition
/// authority. Ordinary `CfmdSchema` values remain valid typed contracts but cannot create a DB.
pub trait DatabaseDefinition: CfmdSchema {}

impl<S> DatabaseDefinition for S
where
    S: CfmdSchema,
    S::DefinitionAuthority: CompleteSchemaAuthority,
{
}

/// A live typed collection bound to one concrete database authority.
///
/// It deliberately does not retain a read snapshot. Each read/query starts from the database's
/// current committed world; transaction mutations still bind through the transaction's exact
/// formation world.
#[doc(hidden)]
#[derive(Debug, Clone)]
#[allow(
    clippy::large_enum_variant,
    reason = "Preserve inline state ownership without adding allocations."
)]
pub enum ContextSource {
    Current(Arc<Database>),
    Snapshot(ReadContext),
}

impl ContextSource {
    fn projected_objects<E: Object>(&self) -> Result<ObjectSet<E>> {
        match self {
            Self::Current(database) => database.projected_objects::<E>(),
            Self::Snapshot(snapshot) => snapshot.projected_objects::<E>(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct EntitySet<E: Object> {
    source: Arc<ContextSource>,
    _entity: PhantomData<fn() -> E>,
}

impl<E: Object> EntitySet<E> {
    #[doc(hidden)]
    pub fn __bind(source: Arc<ContextSource>) -> Result<Self> {
        // Bind by durable semantic field identity. Context contracts may omit persisted fields.
        let _ = source.projected_objects::<E>()?;
        Ok(Self {
            source,
            _entity: PhantomData,
        })
    }

    fn current(&self) -> Result<ObjectSet<E>> {
        self.source.projected_objects::<E>()
    }

    pub fn query(&self) -> Result<ObjectQuery<E>> {
        Ok(self.current()?.query())
    }

    pub fn where_<F, P>(&self, predicate: F) -> Result<ObjectQuery<E>>
    where
        F: FnOnce(&E::Proxy) -> P,
        P: crate::ObjectPredicate<E>,
    {
        Ok(self.current()?.where_(predicate))
    }

    pub fn top<F, V>(&self, k: usize, field: F) -> Result<ObjectQuery<E>>
    where
        F: FnOnce(&E::Proxy) -> crate::Field<E, V>,
        V: OrderedObjectValue,
    {
        Ok(self.current()?.top(k, field))
    }

    pub fn bottom<F, V>(&self, k: usize, field: F) -> Result<ObjectQuery<E>>
    where
        F: FnOnce(&E::Proxy) -> crate::Field<E, V>,
        V: OrderedObjectValue,
    {
        Ok(self.current()?.bottom(k, field))
    }

    pub fn select<F, P>(&self, projection: F) -> Result<ObjectProjectionQuery<E, P>>
    where
        F: FnOnce(&E::Proxy) -> P,
        P: Projection<E>,
    {
        Ok(self.current()?.select(projection))
    }

    pub fn group_by<F, G>(&self, key: F) -> Result<ObjectGroupQuery<E, G>>
    where
        F: FnOnce(&E::Proxy) -> G,
        G: GroupKey<E>,
    {
        Ok(self.current()?.group_by(key))
    }

    pub fn all(&self) -> Result<Vec<E>> {
        self.current()?.all()
    }

    pub fn count(&self) -> Result<usize> {
        self.current()?.count()
    }

    pub fn get(&self, id: crate::Id<E>) -> Result<Option<E>> {
        self.current()?.get(id)
    }

    pub fn require(&self, id: crate::Id<E>) -> Result<E> {
        self.current()?.require(id)
    }

    pub fn set<V, F, P>(
        &self,
        transaction: &mut Transaction,
        id: crate::Id<E>,
        field: F,
        value: V,
    ) -> Result<()>
    where
        V: crate::ObjectValue,
        F: FnOnce(&E::Proxy) -> P,
        P: crate::ObjectPatchField<E, V>,
    {
        self.current()?.set(transaction, id, field, value)
    }

    pub fn add(&self, transaction: &mut Transaction, value: E) -> Result<()> {
        self.current()?.add(transaction, value)
    }

    pub fn remove(&self, transaction: &mut Transaction, value: E) -> Result<()> {
        self.current()?.remove(transaction, value)
    }
}

/// One exact immutable semantic world projected through the same typed consumer surface.
///
/// Ordinary reads should use [`Context`] directly. A snapshot is explicit only when the
/// caller needs several operations to share one committed revision, or selects a historical world
/// through `Context::at`. Authorization remains owned by the database/session rather than by the
/// snapshot token.
pub struct Snapshot<S: CfmdSchema> {
    context: ReadContext,
    surface: S,
}

impl<S: CfmdSchema> Snapshot<S> {
    fn bind(context: ReadContext) -> Result<Self> {
        let surface = S::__bind(Arc::new(ContextSource::Snapshot(context.clone())))?;
        Ok(Self { context, surface })
    }

    #[must_use]
    pub fn revision(&self) -> RevisionId {
        self.context.revision()
    }
}

impl<S: CfmdSchema> From<Snapshot<S>> for Transaction {
    fn from(snapshot: Snapshot<S>) -> Self {
        Transaction::from(snapshot.context)
    }
}

impl<S: CfmdSchema> std::fmt::Debug for Snapshot<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Snapshot")
            .field("revision", &self.revision())
            .field("schema", &std::any::type_name::<S>())
            .finish_non_exhaustive()
    }
}

impl<S: CfmdSchema> Deref for Snapshot<S> {
    type Target = S;

    fn deref(&self) -> &Self::Target {
        &self.surface
    }
}

/// A typed application context bound to one already-open database.
///
/// Unlike database-definition authority, the context surface may describe only the semantic
/// fields known to this consumer. Binding is by durable field semantics, not by ordinal columns.
pub struct Context<S: CfmdSchema> {
    database: Arc<Database>,
    surface: S,
}

impl<S: CfmdSchema> std::fmt::Debug for Context<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Context")
            .field("database", &self.database)
            .field("schema", &std::any::type_name::<S>())
            .finish_non_exhaustive()
    }
}

impl<S: CfmdSchema> Context<S> {
    fn bind(database: Database) -> Result<Self> {
        let database = Arc::new(database);
        let surface = S::__bind(Arc::new(ContextSource::Current(Arc::clone(&database))))?;
        Ok(Self { database, surface })
    }

    #[must_use]
    pub fn database(&self) -> &Database {
        &self.database
    }

    pub fn snapshot(&self) -> Result<Snapshot<S>> {
        Snapshot::bind(self.database.snapshot()?)
    }

    pub fn at(&self, revision: RevisionId) -> Result<Snapshot<S>> {
        Snapshot::bind(self.database.at(revision)?)
    }

    pub fn current_revision(&self) -> Result<RevisionId> {
        self.database.current_revision()
    }

    pub fn history(&self) -> Result<History> {
        self.database.history()
    }

    pub fn preview(&self, transaction: &Transaction) -> Result<CandidatePreview> {
        self.database.preview(transaction)
    }

    pub fn commit(&self, transaction: &Transaction) -> Result<CommitOutcome> {
        self.database.commit(transaction)
    }
}

impl<S: CfmdSchema> Deref for Context<S> {
    type Target = S;

    fn deref(&self) -> &Self::Target {
        &self.surface
    }
}

impl Database {
    /// Binds a typed consumer contract to this already-open database. The contract is allowed to
    /// omit persisted fields; every declared local field must match one durable semantic field.
    pub fn context<S: CfmdSchema>(&self) -> Result<Context<S>> {
        Context::bind(self.clone())
    }
}

/// Database builder whose schema membership is fixed by `S` rather than assembled by calls to
/// `SchemaBuilder::object::<T>()` in application code.
pub struct SchemaDatabaseBuilder<S: CfmdSchema> {
    inner: DatabaseBuilder,
    _schema: PhantomData<fn() -> S>,
}

impl<S: CfmdSchema> std::fmt::Debug for SchemaDatabaseBuilder<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SchemaDatabaseBuilder")
            .field("database", &self.inner)
            .field("schema", &std::any::type_name::<S>())
            .finish_non_exhaustive()
    }
}

impl<S: CfmdSchema> SchemaDatabaseBuilder<S> {
    fn new(path: impl Into<PathBuf>) -> Self {
        Self {
            inner: Database::builder(path),
            _schema: PhantomData,
        }
    }

    #[must_use]
    pub fn storage(mut self, storage: Storage) -> Self {
        self.inner = self.inner.storage(storage);
        self
    }

    #[must_use]
    pub fn encryption(mut self, encryption: Encryption) -> Self {
        self.inner = self.inner.encryption(encryption);
        self
    }

    #[must_use]
    pub fn publication_notifier(mut self, notifier: Arc<dyn PublicationNotifier>) -> Self {
        self.inner = self.inner.publication_notifier(notifier);
        self
    }

    pub fn open(self) -> Result<SchemaDatabase<S>> {
        let database = self.inner.open()?;
        database.__require_schema_definition(S::definition()?)?;
        SchemaDatabase::bind(database)
    }
}

impl<S: DatabaseDefinition> SchemaDatabaseBuilder<S> {
    pub fn create(self) -> Result<SchemaDatabase<S>> {
        let definition = S::definition()?;
        let database = self.inner.schema(definition).create()?;
        SchemaDatabase::bind(database)
    }
}

/// A concrete database together with the explicitly selected typed collection surface `S`.
pub struct SchemaDatabase<S: CfmdSchema> {
    database: Arc<Database>,
    surface: S,
}

impl<S: CfmdSchema> std::fmt::Debug for SchemaDatabase<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SchemaDatabase")
            .field("database", &self.database)
            .field("schema", &std::any::type_name::<S>())
            .finish_non_exhaustive()
    }
}

impl<S: CfmdSchema> SchemaDatabase<S> {
    fn bind(database: Database) -> Result<Self> {
        let database = Arc::new(database);
        let surface = S::__bind(Arc::new(ContextSource::Current(Arc::clone(&database))))?;
        Ok(Self { database, surface })
    }

    /// Explicit escape hatch for hosting/tooling APIs that intentionally operate on raw Database.
    #[must_use]
    pub fn raw(&self) -> &Database {
        &self.database
    }

    pub fn snapshot(&self) -> Result<Snapshot<S>> {
        Snapshot::bind(self.database.snapshot()?)
    }

    pub fn at(&self, revision: RevisionId) -> Result<Snapshot<S>> {
        Snapshot::bind(self.database.at(revision)?)
    }

    pub fn current_revision(&self) -> Result<RevisionId> {
        self.database.current_revision()
    }

    pub fn history(&self) -> Result<History> {
        self.database.history()
    }

    pub fn undo(&self, transaction: &mut Transaction, entry: &HistoryEntry) -> Result<()> {
        self.database.undo(transaction, entry)
    }

    pub fn undo_latest(&self, transaction: &mut Transaction) -> Result<()> {
        self.database.undo_latest(transaction)
    }

    pub fn transaction_readiness(&self, transaction: &Transaction) -> Result<TransactionReadiness> {
        self.database.transaction_readiness(transaction)
    }

    pub fn preview(&self, transaction: &Transaction) -> Result<CandidatePreview> {
        self.database.preview(transaction)
    }

    pub fn commit(&self, transaction: &Transaction) -> Result<CommitOutcome> {
        self.database.commit(transaction)
    }
}

impl<S: CfmdSchema> Deref for SchemaDatabase<S> {
    type Target = S;

    fn deref(&self) -> &Self::Target {
        &self.surface
    }
}
